// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nest/api/grpc/common.proto

// Protobuf Java Version: 3.25.1
package com.example.nest.api;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigOptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.ConfigOption)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string label = 1;</code>
     * @return The label.
     */
    java.lang.String getLabel();
    /**
     * <code>string label = 1;</code>
     * @return The bytes for label.
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string value = 3;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 3;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>repeated string select = 5;</code>
     * @return A list containing the select.
     */
    java.util.List<java.lang.String>
        getSelectList();
    /**
     * <code>repeated string select = 5;</code>
     * @return The count of select.
     */
    int getSelectCount();
    /**
     * <code>repeated string select = 5;</code>
     * @param index The index of the element to return.
     * @return The select at the given index.
     */
    java.lang.String getSelect(int index);
    /**
     * <code>repeated string select = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the select at the given index.
     */
    com.google.protobuf.ByteString
        getSelectBytes(int index);

    /**
     * <code>string group = 6;</code>
     * @return The group.
     */
    java.lang.String getGroup();
    /**
     * <code>string group = 6;</code>
     * @return The bytes for group.
     */
    com.google.protobuf.ByteString
        getGroupBytes();
  }
  /**
   * Protobuf type {@code common.ConfigOption}
   */
  public static final class ConfigOption extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:common.ConfigOption)
      ConfigOptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigOption.newBuilder() to construct.
    private ConfigOption(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigOption() {
      label_ = "";
      name_ = "";
      value_ = "";
      select_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      group_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfigOption();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.nest.api.Common.internal_static_common_ConfigOption_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.nest.api.Common.internal_static_common_ConfigOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.nest.api.Common.ConfigOption.class, com.example.nest.api.Common.ConfigOption.Builder.class);
    }

    public static final int LABEL_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object label_ = "";
    /**
     * <code>string label = 1;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <code>string label = 1;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object value_ = "";
    /**
     * <code>string value = 3;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 3;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_ = 0;
    /**
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int SELECT_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList select_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string select = 5;</code>
     * @return A list containing the select.
     */
    public com.google.protobuf.ProtocolStringList
        getSelectList() {
      return select_;
    }
    /**
     * <code>repeated string select = 5;</code>
     * @return The count of select.
     */
    public int getSelectCount() {
      return select_.size();
    }
    /**
     * <code>repeated string select = 5;</code>
     * @param index The index of the element to return.
     * @return The select at the given index.
     */
    public java.lang.String getSelect(int index) {
      return select_.get(index);
    }
    /**
     * <code>repeated string select = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the select at the given index.
     */
    public com.google.protobuf.ByteString
        getSelectBytes(int index) {
      return select_.getByteString(index);
    }

    public static final int GROUP_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object group_ = "";
    /**
     * <code>string group = 6;</code>
     * @return The group.
     */
    @java.lang.Override
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <code>string group = 6;</code>
     * @return The bytes for group.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(label_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, label_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, value_);
      }
      if (type_ != 0) {
        output.writeInt32(4, type_);
      }
      for (int i = 0; i < select_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, select_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(group_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, group_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(label_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, label_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, value_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < select_.size(); i++) {
          dataSize += computeStringSizeNoTag(select_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSelectList().size();
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(group_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, group_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.nest.api.Common.ConfigOption)) {
        return super.equals(obj);
      }
      com.example.nest.api.Common.ConfigOption other = (com.example.nest.api.Common.ConfigOption) obj;

      if (!getLabel()
          .equals(other.getLabel())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (getType()
          != other.getType()) return false;
      if (!getSelectList()
          .equals(other.getSelectList())) return false;
      if (!getGroup()
          .equals(other.getGroup())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      if (getSelectCount() > 0) {
        hash = (37 * hash) + SELECT_FIELD_NUMBER;
        hash = (53 * hash) + getSelectList().hashCode();
      }
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.nest.api.Common.ConfigOption parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.nest.api.Common.ConfigOption parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.nest.api.Common.ConfigOption parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.nest.api.Common.ConfigOption parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.nest.api.Common.ConfigOption parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.nest.api.Common.ConfigOption parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.nest.api.Common.ConfigOption parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.nest.api.Common.ConfigOption parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.nest.api.Common.ConfigOption parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.nest.api.Common.ConfigOption parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.nest.api.Common.ConfigOption parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.nest.api.Common.ConfigOption parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.nest.api.Common.ConfigOption prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.ConfigOption}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.ConfigOption)
        com.example.nest.api.Common.ConfigOptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.nest.api.Common.internal_static_common_ConfigOption_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.nest.api.Common.internal_static_common_ConfigOption_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.nest.api.Common.ConfigOption.class, com.example.nest.api.Common.ConfigOption.Builder.class);
      }

      // Construct using com.example.nest.api.Common.ConfigOption.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        label_ = "";
        name_ = "";
        value_ = "";
        type_ = 0;
        select_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        group_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.nest.api.Common.internal_static_common_ConfigOption_descriptor;
      }

      @java.lang.Override
      public com.example.nest.api.Common.ConfigOption getDefaultInstanceForType() {
        return com.example.nest.api.Common.ConfigOption.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.nest.api.Common.ConfigOption build() {
        com.example.nest.api.Common.ConfigOption result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.nest.api.Common.ConfigOption buildPartial() {
        com.example.nest.api.Common.ConfigOption result = new com.example.nest.api.Common.ConfigOption(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.nest.api.Common.ConfigOption result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.label_ = label_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          select_.makeImmutable();
          result.select_ = select_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.group_ = group_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.nest.api.Common.ConfigOption) {
          return mergeFrom((com.example.nest.api.Common.ConfigOption)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.nest.api.Common.ConfigOption other) {
        if (other == com.example.nest.api.Common.ConfigOption.getDefaultInstance()) return this;
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.select_.isEmpty()) {
          if (select_.isEmpty()) {
            select_ = other.select_;
            bitField0_ |= 0x00000010;
          } else {
            ensureSelectIsMutable();
            select_.addAll(other.select_);
          }
          onChanged();
        }
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                label_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                type_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureSelectIsMutable();
                select_.add(s);
                break;
              } // case 42
              case 50: {
                group_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object label_ = "";
      /**
       * <code>string label = 1;</code>
       * @return The label.
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string label = 1;</code>
       * @return The bytes for label.
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string label = 1;</code>
       * @param value The label to set.
       * @return This builder for chaining.
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        label_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string label = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLabel() {
        label_ = getDefaultInstance().getLabel();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string label = 1;</code>
       * @param value The bytes for label to set.
       * @return This builder for chaining.
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        label_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 3;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 3;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 3;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string value = 3;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 4;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 4;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {

        type_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList select_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureSelectIsMutable() {
        if (!select_.isModifiable()) {
          select_ = new com.google.protobuf.LazyStringArrayList(select_);
        }
        bitField0_ |= 0x00000010;
      }
      /**
       * <code>repeated string select = 5;</code>
       * @return A list containing the select.
       */
      public com.google.protobuf.ProtocolStringList
          getSelectList() {
        select_.makeImmutable();
        return select_;
      }
      /**
       * <code>repeated string select = 5;</code>
       * @return The count of select.
       */
      public int getSelectCount() {
        return select_.size();
      }
      /**
       * <code>repeated string select = 5;</code>
       * @param index The index of the element to return.
       * @return The select at the given index.
       */
      public java.lang.String getSelect(int index) {
        return select_.get(index);
      }
      /**
       * <code>repeated string select = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the select at the given index.
       */
      public com.google.protobuf.ByteString
          getSelectBytes(int index) {
        return select_.getByteString(index);
      }
      /**
       * <code>repeated string select = 5;</code>
       * @param index The index to set the value at.
       * @param value The select to set.
       * @return This builder for chaining.
       */
      public Builder setSelect(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSelectIsMutable();
        select_.set(index, value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string select = 5;</code>
       * @param value The select to add.
       * @return This builder for chaining.
       */
      public Builder addSelect(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSelectIsMutable();
        select_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string select = 5;</code>
       * @param values The select to add.
       * @return This builder for chaining.
       */
      public Builder addAllSelect(
          java.lang.Iterable<java.lang.String> values) {
        ensureSelectIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, select_);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string select = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSelect() {
        select_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string select = 5;</code>
       * @param value The bytes of the select to add.
       * @return This builder for chaining.
       */
      public Builder addSelectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureSelectIsMutable();
        select_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object group_ = "";
      /**
       * <code>string group = 6;</code>
       * @return The group.
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string group = 6;</code>
       * @return The bytes for group.
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string group = 6;</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        group_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string group = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        group_ = getDefaultInstance().getGroup();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string group = 6;</code>
       * @param value The bytes for group to set.
       * @return This builder for chaining.
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        group_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:common.ConfigOption)
    }

    // @@protoc_insertion_point(class_scope:common.ConfigOption)
    private static final com.example.nest.api.Common.ConfigOption DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.nest.api.Common.ConfigOption();
    }

    public static com.example.nest.api.Common.ConfigOption getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigOption>
        PARSER = new com.google.protobuf.AbstractParser<ConfigOption>() {
      @java.lang.Override
      public ConfigOption parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ConfigOption> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigOption> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.nest.api.Common.ConfigOption getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MappedConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.MappedConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
     */
    int getConfigCount();
    /**
     * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
     */
    boolean containsConfig(
        java.lang.String key);
    /**
     * Use {@link #getConfigMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.example.nest.api.Common.ConfigOption>
    getConfig();
    /**
     * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
     */
    java.util.Map<java.lang.String, com.example.nest.api.Common.ConfigOption>
    getConfigMap();
    /**
     * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
     */
    /* nullable */
com.example.nest.api.Common.ConfigOption getConfigOrDefault(
        java.lang.String key,
        /* nullable */
com.example.nest.api.Common.ConfigOption defaultValue);
    /**
     * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
     */
    com.example.nest.api.Common.ConfigOption getConfigOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code common.MappedConfig}
   */
  public static final class MappedConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:common.MappedConfig)
      MappedConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MappedConfig.newBuilder() to construct.
    private MappedConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MappedConfig() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MappedConfig();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.nest.api.Common.internal_static_common_MappedConfig_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetConfig();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.nest.api.Common.internal_static_common_MappedConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.nest.api.Common.MappedConfig.class, com.example.nest.api.Common.MappedConfig.Builder.class);
    }

    public static final int CONFIG_FIELD_NUMBER = 1;
    private static final class ConfigDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.example.nest.api.Common.ConfigOption> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.example.nest.api.Common.ConfigOption>newDefaultInstance(
                  com.example.nest.api.Common.internal_static_common_MappedConfig_ConfigEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.example.nest.api.Common.ConfigOption.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.example.nest.api.Common.ConfigOption> config_;
    private com.google.protobuf.MapField<java.lang.String, com.example.nest.api.Common.ConfigOption>
    internalGetConfig() {
      if (config_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ConfigDefaultEntryHolder.defaultEntry);
      }
      return config_;
    }
    public int getConfigCount() {
      return internalGetConfig().getMap().size();
    }
    /**
     * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
     */
    @java.lang.Override
    public boolean containsConfig(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetConfig().getMap().containsKey(key);
    }
    /**
     * Use {@link #getConfigMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.example.nest.api.Common.ConfigOption> getConfig() {
      return getConfigMap();
    }
    /**
     * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.example.nest.api.Common.ConfigOption> getConfigMap() {
      return internalGetConfig().getMap();
    }
    /**
     * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.example.nest.api.Common.ConfigOption getConfigOrDefault(
        java.lang.String key,
        /* nullable */
com.example.nest.api.Common.ConfigOption defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.example.nest.api.Common.ConfigOption> map =
          internalGetConfig().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
     */
    @java.lang.Override
    public com.example.nest.api.Common.ConfigOption getConfigOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.example.nest.api.Common.ConfigOption> map =
          internalGetConfig().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetConfig(),
          ConfigDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.example.nest.api.Common.ConfigOption> entry
           : internalGetConfig().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.example.nest.api.Common.ConfigOption>
        config__ = ConfigDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, config__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.nest.api.Common.MappedConfig)) {
        return super.equals(obj);
      }
      com.example.nest.api.Common.MappedConfig other = (com.example.nest.api.Common.MappedConfig) obj;

      if (!internalGetConfig().equals(
          other.internalGetConfig())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetConfig().getMap().isEmpty()) {
        hash = (37 * hash) + CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + internalGetConfig().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.nest.api.Common.MappedConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.nest.api.Common.MappedConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.nest.api.Common.MappedConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.nest.api.Common.MappedConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.nest.api.Common.MappedConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.nest.api.Common.MappedConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.nest.api.Common.MappedConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.nest.api.Common.MappedConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.nest.api.Common.MappedConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.nest.api.Common.MappedConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.nest.api.Common.MappedConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.nest.api.Common.MappedConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.nest.api.Common.MappedConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.MappedConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.MappedConfig)
        com.example.nest.api.Common.MappedConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.nest.api.Common.internal_static_common_MappedConfig_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetConfig();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableConfig();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.nest.api.Common.internal_static_common_MappedConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.nest.api.Common.MappedConfig.class, com.example.nest.api.Common.MappedConfig.Builder.class);
      }

      // Construct using com.example.nest.api.Common.MappedConfig.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableConfig().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.nest.api.Common.internal_static_common_MappedConfig_descriptor;
      }

      @java.lang.Override
      public com.example.nest.api.Common.MappedConfig getDefaultInstanceForType() {
        return com.example.nest.api.Common.MappedConfig.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.nest.api.Common.MappedConfig build() {
        com.example.nest.api.Common.MappedConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.nest.api.Common.MappedConfig buildPartial() {
        com.example.nest.api.Common.MappedConfig result = new com.example.nest.api.Common.MappedConfig(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.nest.api.Common.MappedConfig result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.config_ = internalGetConfig().build(ConfigDefaultEntryHolder.defaultEntry);
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.nest.api.Common.MappedConfig) {
          return mergeFrom((com.example.nest.api.Common.MappedConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.nest.api.Common.MappedConfig other) {
        if (other == com.example.nest.api.Common.MappedConfig.getDefaultInstance()) return this;
        internalGetMutableConfig().mergeFrom(
            other.internalGetConfig());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, com.example.nest.api.Common.ConfigOption>
                config__ = input.readMessage(
                    ConfigDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableConfig().ensureBuilderMap().put(
                    config__.getKey(), config__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private static final class ConfigConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.example.nest.api.Common.ConfigOptionOrBuilder, com.example.nest.api.Common.ConfigOption> {
        @java.lang.Override
        public com.example.nest.api.Common.ConfigOption build(com.example.nest.api.Common.ConfigOptionOrBuilder val) {
          if (val instanceof com.example.nest.api.Common.ConfigOption) { return (com.example.nest.api.Common.ConfigOption) val; }
          return ((com.example.nest.api.Common.ConfigOption.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.String, com.example.nest.api.Common.ConfigOption> defaultEntry() {
          return ConfigDefaultEntryHolder.defaultEntry;
        }
      };
      private static final ConfigConverter configConverter = new ConfigConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.String, com.example.nest.api.Common.ConfigOptionOrBuilder, com.example.nest.api.Common.ConfigOption, com.example.nest.api.Common.ConfigOption.Builder> config_;
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.example.nest.api.Common.ConfigOptionOrBuilder, com.example.nest.api.Common.ConfigOption, com.example.nest.api.Common.ConfigOption.Builder>
          internalGetConfig() {
        if (config_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(configConverter);
        }
        return config_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.example.nest.api.Common.ConfigOptionOrBuilder, com.example.nest.api.Common.ConfigOption, com.example.nest.api.Common.ConfigOption.Builder>
          internalGetMutableConfig() {
        if (config_ == null) {
          config_ = new com.google.protobuf.MapFieldBuilder<>(configConverter);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return config_;
      }
      public int getConfigCount() {
        return internalGetConfig().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
       */
      @java.lang.Override
      public boolean containsConfig(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetConfig().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getConfigMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.example.nest.api.Common.ConfigOption> getConfig() {
        return getConfigMap();
      }
      /**
       * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.example.nest.api.Common.ConfigOption> getConfigMap() {
        return internalGetConfig().getImmutableMap();
      }
      /**
       * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
com.example.nest.api.Common.ConfigOption getConfigOrDefault(
          java.lang.String key,
          /* nullable */
com.example.nest.api.Common.ConfigOption defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.example.nest.api.Common.ConfigOptionOrBuilder> map = internalGetMutableConfig().ensureBuilderMap();
        return map.containsKey(key) ? configConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
       */
      @java.lang.Override
      public com.example.nest.api.Common.ConfigOption getConfigOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.example.nest.api.Common.ConfigOptionOrBuilder> map = internalGetMutableConfig().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return configConverter.build(map.get(key));
      }
      public Builder clearConfig() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableConfig().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
       */
      public Builder removeConfig(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableConfig().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.example.nest.api.Common.ConfigOption>
          getMutableConfig() {
        bitField0_ |= 0x00000001;
        return internalGetMutableConfig().ensureMessageMap();
      }
      /**
       * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
       */
      public Builder putConfig(
          java.lang.String key,
          com.example.nest.api.Common.ConfigOption value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableConfig().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
       */
      public Builder putAllConfig(
          java.util.Map<java.lang.String, com.example.nest.api.Common.ConfigOption> values) {
        for (java.util.Map.Entry<java.lang.String, com.example.nest.api.Common.ConfigOption> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutableConfig().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, .common.ConfigOption&gt; config = 1;</code>
       */
      public com.example.nest.api.Common.ConfigOption.Builder putConfigBuilderIfAbsent(
          java.lang.String key) {
        java.util.Map<java.lang.String, com.example.nest.api.Common.ConfigOptionOrBuilder> builderMap = internalGetMutableConfig().ensureBuilderMap();
        com.example.nest.api.Common.ConfigOptionOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = com.example.nest.api.Common.ConfigOption.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof com.example.nest.api.Common.ConfigOption) {
          entry = ((com.example.nest.api.Common.ConfigOption) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (com.example.nest.api.Common.ConfigOption.Builder) entry;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:common.MappedConfig)
    }

    // @@protoc_insertion_point(class_scope:common.MappedConfig)
    private static final com.example.nest.api.Common.MappedConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.nest.api.Common.MappedConfig();
    }

    public static com.example.nest.api.Common.MappedConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MappedConfig>
        PARSER = new com.google.protobuf.AbstractParser<MappedConfig>() {
      @java.lang.Override
      public MappedConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MappedConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MappedConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.nest.api.Common.MappedConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_ConfigOption_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_ConfigOption_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_MappedConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_MappedConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_MappedConfig_ConfigEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_MappedConfig_ConfigEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032nest/api/grpc/common.proto\022\006common\"g\n\014" +
      "ConfigOption\022\r\n\005label\030\001 \001(\t\022\014\n\004name\030\002 \001(" +
      "\t\022\r\n\005value\030\003 \001(\t\022\014\n\004type\030\004 \001(\005\022\016\n\006select" +
      "\030\005 \003(\t\022\r\n\005group\030\006 \001(\t\"\205\001\n\014MappedConfig\0220" +
      "\n\006config\030\001 \003(\0132 .common.MappedConfig.Con" +
      "figEntry\032C\n\013ConfigEntry\022\013\n\003key\030\001 \001(\t\022#\n\005" +
      "value\030\002 \001(\0132\024.common.ConfigOption:\0028\001B\026\n" +
      "\024com.example.nest.apib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_common_ConfigOption_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_ConfigOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_ConfigOption_descriptor,
        new java.lang.String[] { "Label", "Name", "Value", "Type", "Select", "Group", });
    internal_static_common_MappedConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_MappedConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_MappedConfig_descriptor,
        new java.lang.String[] { "Config", });
    internal_static_common_MappedConfig_ConfigEntry_descriptor =
      internal_static_common_MappedConfig_descriptor.getNestedTypes().get(0);
    internal_static_common_MappedConfig_ConfigEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_MappedConfig_ConfigEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
