#HikariCP pool
#HikariCP.jdbcUrl=jdbc:mysql://localhost:3306/bgp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#HikariCP.username=root
#HikariCP.password=123456
HikariCP.jdbcUrl=jdbc:mysql://rm-2zej93vs9m24a384w9o.mysql.rds.aliyuncs.com:3306/bgp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
HikariCP.username=bgp_dev
HikariCP.password=BgpNet@2024
#HikariCP.jdbcUrl=jdbc:mysql://100.146.4.40:9000/bgp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#HikariCP.username=root
#HikariCP.password=123456
HikariCP.connectionTestQuery=select 1
HikariCP.maxPoolSize=20
HikariCP.driverClassName=com.mysql.cj.jdbc.Driver
HikariCP.autoCommit=false
HikariCP.cachePrepStmts=true
HikariCP.prepStmtCacheSize=250
HikariCP.prepStmtCacheSqlLimit=204800
HikariCP.useServerPrepStmts=true